### ISSUE TITLE
It doesn't work with bloodhound when fetching data from remote only

### ISSUE THREAD

**Issue by wei-hai** [bassjobsen/Bootstrap-3-Typeahead#240]
the data is fetched but never shown in the dropdown list

**Comment by bsherrill480** [comment]
Having the same problem.

**Comment by luisepbueno** [comment]
That happens because Bloodhound expects Typeahead source function to receive three parameters: query, sync and async. But actually Bootstrap 3 Typeahead source functions works with only two parameters: query and process.

Look for 

`this.source(this.query, $.proxy(this.process, this));`

and replace with

`this.source(this.query, **null**, $.proxy(this.process, this));`

That should fix the issue when using Bootstrap 3 Typeahed with Bloodhound and remote datasets.

**Comment by quidproquo** [comment]
The above didn't work for me, I get an error
`bloodhound.self.js?body=1:880 Uncaught TypeError: sync is not a function(…)`

**Comment by mockiemockiz** [comment]
same, the solution did not work as well.

**Comment by wei-hai** [comment]
I suggest using the original project by twitter which works well.
https://github.com/twitter/typeahead.js
